# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import joblib
import numpy as np

model = joblib.load("RF_class.pkl")

def main():
    st.title("Machine Learning Model Deployment")

    sepal_length = st.slider("Sepal Length", min_value=0.0, max_value=10.0, value=0.1)
    sepal_width = st.slider("Sepal Width", min_value=0.0, max_value=10.0, value=0.1)
    petal_length = st.slider("Petal Length", min_value=0.0, max_value=10.0, value=0.1)
    petal_width = st.slider("Petal Width", min_value=0.0, max_value=10.0, value=0.1)

    if st.button("Make Prediction"):
        features = [sepal_length, sepal_width, petal_length, petal_width]
        result = make_prediction(features)
        st.success(f"The Prediction is: {result}")

def make_prediction(features):
    input_array = np.array(features).reshape(1, -1)
    prediction = model.predict(input_array)
    return prediction[0]

if _name_ == "_main_":
    main()